Repository leecrossun/HealthStock, pull requests merged in 2021-05, with the labels that each got.

#14 #7 user
  app/src/main/java/ddwucom/mobile/healthstock/dto/UserInfo.java
Labels: develop

#20 product dto finished
  app/src/main/java/ddwucom/mobile/healthstock/dto/Product.java
Labels: develop

#22 exerciseLayout
  app/src/main/res/layout/activity_heartrate.xml
  app/src/main/res/layout/activity_heartresult.xml
Labels: develop

#29 user page xml
  app/build.gradle
  app/src/main/res/layout/user_page.xml
Labels: xml

#31 linearlayout error solved
  app/src/main/res/layout/user_page.xml
  exit
Labels: error
